### ISSUE TITLE
Should we be wrapping text to 80 characters?

### ISSUE THREAD

**Issue by DanielSank** [digitalphase/digitalphase.github.io#12]
I don't see a reason to do this in md files, so I vote no.

**Comment by lovesegfault** [comment]
It doesn't make a difference in presentation, i.e. the file will be displayed the same, and it makes it much easier to edit from the terminal, which is why I'm all for 80 char wrapping whenever possible.

**Comment by DanielSank** [comment]
I think we decided not to. Let's add hard newlines at the end of each sentence though.
